# NumPy

NumPy (Numerical Python) is a fundamental library for numerical computing in Python. Here are the key points:

* N-Dimensional Arrays: Provides support for multi-dimensional arrays (ndarray) for efficient storage and manipulation.
* Homogeneous Data: All elements in a NumPy array must be of the same type.
Performance: Arrays are stored in contiguous memory, making them faster and more memory-efficient than Python lists.
* Broadcasting: Allows operations on arrays of different shapes without needing explicit replication of data.
* Mathematical Functions: Offers a wide range of functions for mathematical operations, statistical analysis, and linear algebra.
* Array Creation:
From lists: np.array()
Zeros: np.zeros()
Ones: np.ones()
Ranges: np.arange()
Evenly spaced values: np.linspace()

Installing Numpy:  pip install numpy

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
import time

# NumPy Array vs. Python List

## Key Differences

1. **Data Type**
   - **NumPy Array**: Homogeneous (same data type).
   - **Python List**: Heterogeneous (mixed data types).

2. **Performance**
   - **NumPy Array**: Faster and more memory-efficient.
   - **Python List**: Slower for numerical operations.

3. **Functionality**
   - **NumPy Array**: Supports mathematical operations and broadcasting.
   - **Python List**: Basic operations, no built-in numerical functions.

4. **Dimensionality**
   - **NumPy Array**: Multi-dimensional (n-dimensional).
   - **Python List**: Primarily one-dimensional (nested lists for multi-dimensional).

In [ ]:
# Size of the array
size = 10**6

# Create a list and a NumPy array with the same values
list_data = list(range(size))
np_array = np.arange(size)

# Function to add elements in a Python list
def list_addition():
    return [x + 1 for x in list_data]

# Function to add elements in a NumPy array
def numpy_addition():
    return np_array + 1

# Timing the list addition
start_time = time.time()
list_result = list_addition()
list_time = time.time() - start_time
print(f"Time taken for list addition: {list_time:.6f} seconds")

# Timing the NumPy addition
start_time = time.time()
numpy_result = numpy_addition()
numpy_time = time.time() - start_time
print(f"Time taken for NumPy addition: {numpy_time:.6f} seconds")

# Optional: Check if the results are the same
print(f"Results are the same: {np.array_equal(list_result, numpy_result)}")

Time taken for list addition: 0.064790 seconds
Time taken for NumPy addition: 0.005019 seconds
Results are the same: True


# Array Creation

Numpy Array Initialization

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr3 = np.array([[1,2,3,4,5],[2,3,4,5,6]])

print(arr1)
print(arr1.dtype)

arr2 = np.array([1, 2, 3, 4, 5], dtype='float32')

print("Array:", arr2)
print(arr2.dtype)

print(arr3)
print(arr3.shape)


[1 2 3 4 5]
int64
Array: [1. 2. 3. 4. 5.]
float32
[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


An array with a range of values

In [ ]:
arr2 = np.arange(0, 10, 2)
print("Arange:", arr2)


Arange: [0 2 4 6 8]


An array filled with ones and zeros

In [ ]:
zeros = np.zeros((3, 3))
ones = np.ones((2, 3))
print("Zeros:\n", zeros)
print("Ones:\n", ones)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


A 2D NumPy array of specified shape filled with a constant value.

In [ ]:
full_array = np.full((2, 2), 7)
print("Full Array:\n", full_array)


Full Array:
 [[7 7]
 [7 7]]


An array with evenly spaced values

In [ ]:
linspace_array = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_array)


Linspace Array: [0.   0.25 0.5  0.75 1.  ]


# Array Manipulation

Reshape an Array

In [ ]:
arr1 = np.array([1,2,3,4,5])
print(arr1.shape)
print(end='\n')
reshaped = arr1.reshape(5, 1)
print("Reshaped:\n", reshaped)
print(end="\n")
print(reshaped.shape)

(5,)

Reshaped:
 [[1]
 [2]
 [3]
 [4]
 [5]]

(5, 1)


Flatten an Array

In [ ]:
flattened = reshaped.flatten()
print("Flattened:", flattened)
print(flattened.shape)

Flattened: [1 2 3 4 5]
(5,)


Transpose an Array

In [ ]:
arr3 = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
print(arr3.shape)
print(end="\n")
# Transposing the array
transposed = arr3.transpose()

# Printing the transposed array
print("Transposed:\n", transposed)
print("\n")
print(transposed.shape)


(2, 5)

Transposed:
 [[1 5]
 [2 4]
 [3 3]
 [4 2]
 [5 1]]


(5, 2)


In [ ]:
arr1 = np.array([1,2,3,4,5])
arr3 = np.array([6, 7, 8])
concatenated = np.concatenate((arr1, arr3))
print("Concatenated:", concatenated)


Concatenated: [1 2 3 4 5 6 7 8]


In [ ]:
arr1 = np.array([1,2,3,4,5])
split_array = np.split(arr1, 5)
print("Split Array:", split_array)

Split Array: [array([1]), array([2]), array([3]), array([4]), array([5])]


# Mathematical Functions

1. Element-wise Operations

In [ ]:
import numpy as np

# Creating two NumPy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr3 = np.array([6, 7, 8, 9, 10])

# Element-wise addition
added = np.add(arr1, arr3)
print("Added:", added)

# Element-wise subtraction
subtracted = np.subtract(arr1, arr3)
print("Subtracted:", subtracted)

# Element-wise multiplication
multiplied = np.multiply(arr1, arr3)
print("Multiplied:", multiplied)

# Element-wise division
divided = np.divide(arr1, arr3)
print("Divided:", divided)

# Element-wise modulus
modulus = np.mod(arr3, arr1)
print("Modulus:", modulus)

# Element-wise power
power = np.power(arr1, 2)  # Raising arr1 to the power of 2
print("Power (arr1^2):", power)





Added: [ 7  9 11 13 15]
Subtracted: [-5 -5 -5 -5 -5]
Multiplied: [ 6 14 24 36 50]
Divided: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Modulus: [0 1 2 1 0]
Power (arr1^2): [ 1  4  9 16 25]


In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

sum_value = np.sum(arr1)
mean_value = np.mean(arr1)
median_value = np.median(arr1)
std_value = np.std(arr1)
variance_value = np.var(arr1)
min_value = np.min(arr1)
max_value = np.max(arr1)
argmax_value = np.argmax(arr1)
argmin_value = np.argmin(arr1)
sqrt_values = np.sqrt(arr1)


print("Sum:", sum_value)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_value)
print("Variance:", variance_value)
print("Minimum:", min_value)
print("Maximum:", max_value)
print("Index of Maximum Value:", argmax_value)
print("Index of Minimum Value:", argmin_value)
print("Square Roots:", sqrt_values)


Sum: 55
Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Minimum: 1
Maximum: 10
Index of Maximum Value: 9
Index of Minimum Value: 0
Square Roots: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


# Array Indexing and Slicing

Basic Indexing

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])


element = arr1[2]
print("Element at index 2:", element)


Element at index 2: 3


Slicing of an array

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

slice_array = arr1[1:4]
print("Slice Array:", slice_array)


Slice Array: [2 3 4]


Boolean Indexing

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

bool_index = arr1[arr1 > 3]
print("Boolean Indexing:", bool_index)

Boolean Indexing: [ 4  5  6  7  8  9 10]


#Linear Algebra


In [ ]:
# Create a 2D array (matrix)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# 1. Matrix Multiplication
C = np.matmul(arr1, arr2)  # or C = arr1 @ arr2
print("Matrix Multiplication (arr1 @ arr2):\n", C)

# 2. Matrix Inversion
A_inv = np.linalg.inv(arr1)
print("Inverse of arr1:\n", A_inv)

# 3. Determinant
det_A = np.linalg.det(arr1)
print("Determinant of arr1:", det_A)

# 4. Transpose
A_T = np.transpose(arr1)
print("Transpose of arr1:\n", A_T)


Matrix Multiplication (arr1 @ arr2):
 [[19 22]
 [43 50]]
Inverse of arr1:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of arr1: -2.0000000000000004
Transpose of arr1:
 [[1 3]
 [2 4]]


# Sorting and Searching

 Sorting


In [ ]:
# Create an array
arr = np.array([3, 1, 4, 1, 5, 9, 2])

# Sort the array
sorted_arr = np.sort(arr)
print("Sorted Array:", sorted_arr)

# Get the indices that would sort the array
indices = np.argsort(arr)
print("Indices for Sorted Array:", indices)

Sorted Array: [1 1 2 3 4 5 9]
Indices for Sorted Array: [1 3 6 0 2 4 5]


In [ ]:
# Create two arrays
names = np.array(['John', 'Anna', 'Zoe', 'Amit'])
ages = np.array([28, 22, 22, 30])

# Sort by names, then by ages
sorted_indices = np.lexsort((ages, names))
sorted_names = names[sorted_indices]
sorted_ages = ages[sorted_indices]
print("Sorted Names:", sorted_names)
print("Sorted Ages:", sorted_ages)

Sorted Names: ['Amit' 'Anna' 'John' 'Zoe']
Sorted Ages: [30 22 28 22]


Searching

In [ ]:
arr = np.array([2,5,7,8,1])
indices = np.where(arr > 4)
print("Indices of elements greater than 4:", indices)
print("Elements greater than 4:", arr[indices])

Indices of elements greater than 4: (array([1, 2, 3]),)
Elements greater than 4: [5 7 8]


In [ ]:
# Create a sorted array
sorted_arr = np.array([1, 2, 3, 4, 7,10])

# Find the index to insert 6
index = np.searchsorted(sorted_arr, 6)
print("Index to insert 6:", index)

Index to insert 6: 4


In [ ]:
# Create an array with zeros
arr_with_zeros = np.array([0, 1, 0, 3, 4])

# Get indices of non-zero elements
non_zero_indices = np.nonzero(arr_with_zeros)
print("Indices of non-zero elements:", non_zero_indices)
print("Non-zero elements:", arr_with_zeros[non_zero_indices])

Indices of non-zero elements: (array([1, 3, 4]),)
Non-zero elements: [1 3 4]


# Random Number Generation

In [ ]:
# Generate an array of random floats (2x3)
random_array = np.random.rand(2, 3)
print("Random Array (0 to 1):\n", random_array)


Random Array (0 to 1):
 [[0.74528901 0.11494648 0.52860324]
 [0.24906361 0.08940479 0.08283693]]


In [ ]:
# Generate an array of random integers (from 0 to 10, 2x3)
random_integers = np.random.randint(0, 10, size=(2, 3))
print("\nRandom Integer Array (0 to 9):\n", random_integers)


Random Integer Array (0 to 9):
 [[3 0 1]
 [8 7 3]]


In [ ]:
# Generate a random sample from a given array
sample_array = np.array([10, 20, 30, 40, 50])
random_sample = np.random.choice(sample_array, size=3, replace=False)
print("\nRandom Sample from Given Array:\n", random_sample)


Random Sample from Given Array:
 [50 40 30]
